export const operatorRoles = {
    // Defenders
    Smoke: ["Crowd Control", "Anti-Entry"],
    Mute: ["Crowd Control", "Anti-Gadget"],
    Castle: ["Anti-Entry", "Support"],
    Pulse: ["Intel"],
    Doc: ["Support"],
    Rook: ["Support"],
    Kapkan: ["Trapper"],
    Tachanka: ["Crowd Control"],
    Jager: ["Anti-Gadget"],
    Bandit: ["Anti-Gadget"],
    Frost: ["Trapper"],
    Valkyrie: ["Intel"],
    Caveira: ["Crowd Control", "Intel"],
    Echo: ["Intel"],
    Mira: ["Intel"],
    Lesion: ["Trapper"],
    Ela: ["Trapper", "Crowd Control"],
    Vigil: ["Crowd Control", "Anti-Gadget"],
    Maestro: ["Intel", "Anti-Gadget"],
    Alibi: ["Trapper"],
    Clash: ["Crowd Control", "Intel"],
    Warden: ["Intel"],
    Mozzie: ["Intel", "Anti-Gadget"],
    Goyo: ["Trapper", "Anti-Entry"],
    Wamai: ["Anti-Gadget"],
    Aruni: ["Anti-Entry", "Anti-Gadget"],
    Thunderbird: ["Support"],
    Thorn: ["Trapper"],
    Azami: ["Anti-Entry"],
    Solis: ["Intel"],
    Fenrir: ["Trapper", "Crowd Control"],
    Tubarao: ["Anti-Gadget"],
    Skopos: ["Support"],
    Sentry: ["Intel"],

    // Attackers
    Thermite: ["Hard-Breach", "Support"],
    Hibana: ["Hard-Breach", "Front Line"],
    Ace: ["Hard-Breach", "Anti-Gadget"],
    Ash: ["Breach", "Front Line"],
    Maverick: ["Hard-Breach", "Front Line"],
    Sledge: ["Anti-Gadget", "Breach"],
    Thatcher: ["Support", "Anti-Gadget"],
    Twitch: ["Intel", "Anti-Gadget"],
    Fuze: ["Anti-Gadget"],
    Glaz: ["Intel"],
    IQ: ["Intel"],
    Montagne: ["Support"],
    Blitz: ["Front Line"],
    Capitao: ["Front Line"],
    Ying: ["Front Line"],
    Dokkaebi: ["Intel"],
    Lion: ["Intel", "Map Control"],
    Nomad: ["Map Control", "Front Line"],
    Nokk: ["Map Control", "Front Line"],
    Amaru: ["Map Control", "Front Line"],
    Iana: ["Intel", "Front Line"],
    Zero: ["Intel", "Anti-Gadget"],
    Flores: ["Intel", "Anti-Gadget"],
    Osa: ["Support", "Intel"],
    Kali: ["Support", "Anti-Gadget"],
    Gridlock: ["Support", "Map Control"],
    Finka: ["Support", "Front Line"],
    Buck: ["Support", "Breach"],
    Blackbeard: ["Breach", "Front Line"],
    Zofia: ["Anti-Gadget", "Breach"],
    Deimos: ["Intel", "Map Control"],
    Grim: ["Map Control", "Front Line"],
    Brava: ["Intel", "Anti-Gadget"],
    Ram: ["Anti-Gadget", "Breach"],
    Sens: ["Map Control", "Support"],
    Striker: ["Support"],
    Rauora: ["Support", "Map Control"]
};
