export const operatorRoles = {
    // Defenders
    Kapkan: ["Trapper"],
    Tachanka: ["Crowd Control"],
    Bandit: ["Anti-Breach"],
    Jager: ["Anti-Gadget"],
    Rook: ["Support"],
    Doc: ["Support"],
    Pulse: ["Intel"],
    Castle: ["Anti-Entry", "Support"],
    Smoke: ["Crowd Control", "Anti-Entry"],
    Mute: ["Crowd Control", "Anti-Breach"],
    Frost: ["Trapper"],
    Valkyrie: ["Intel"],
    Caveira: ["Crowd Control", "Intel"],
    Echo: ["Intel"],
    Mira: ["Intel"],
    Lesion: ["Trapper"],
    Ela: ["Trapper", "Crowd Control"],
    Vigil: ["Crowd Control", "Anti-Gadget"],
    Alibi: ["Trapper"],
    Maestro: ["Intel", "Anti-Gadget"],
    Clash: ["Crowd Control", "Intel"],
    Kaid: ["Anti-Entry", "Anti-Breach"],
    Mozzie: ["Intel", "Anti-Gadget"],
    Warden: ["Intel"],
    Goyo: ["Trapper", "Anti-Entry"],
    Wamai: ["Anti-Gadget"],
    Oryx: ["Support"],
    Melusi: ["Intel", "Crown Control"],
    Aruni: ["Anti-Entry", "Anti-Gadget"],
    Thunderbird: ["Support"],
    Thorn: ["Trapper"],
    Azami: ["Anti-Entry"],
    Solis: ["Intel"],
    Fenrir: ["Trapper", "Crowd Control"],
    Tubarao: ["Anti-Breach"],
    Sentry: ["Intel"],
    Skopos: ["Support"],
    Denari: ["Anti-Entry", "Crowd Control"],

    // Attackers
    Glaz: ["Intel"],
    Fuze: ["Anti-Gadget"],
    IQ: ["Intel"],
    Blitz: ["Front Line"],
    Twitch: ["Intel", "Anti-Gadget"],
    Montagne: ["Support"],
    Thermite: ["Hard-Breach", "Support"],
    Ash: ["Breach", "Front Line"],
    Thatcher: ["Support", "Anti-Gadget"],
    Sledge: ["Anti-Gadget", "Breach"],
    Buck: ["Support", "Breach"],
    Blackbeard: ["Breach", "Front Line"],
    Capitao: ["Front Line"],
    Hibana: ["Hard-Breach", "Front Line"],
    Jackal: ["INTEL", "MAP CONTROL"],
    Ying: ["Front Line"],
    Zofia: ["Anti-Gadget", "Breach"],
    Dokkaebi: ["Intel"],
    Finka: ["Support", "Front Line"],
    Lion: ["Intel", "Map Control"],
    Maverick: ["Hard-Breach", "Front Line"],
    Nomad: ["Map Control", "Front Line"],
    Gridlock: ["Support", "Map Control"],
    Nokk: ["Map Control", "Front Line"],
    Amaru: ["Map Control", "Front Line"],
    Kali: ["Support", "Anti-Gadget"],
    Iana: ["Intel", "Front Line"],
    Ace: ["Hard-Breach", "Anti-Gadget"],
    Zero: ["Intel", "Anti-Gadget"],
    Flores: ["Intel", "Anti-Gadget"],
    Osa: ["Support", "Intel"],
    Sens: ["Map Control", "Support"],
    Grim: ["Map Control", "Front Line"],
    Brava: ["Intel", "Anti-Gadget"],
    Ram: ["Anti-Gadget", "Breach"],
    Deimos: ["Intel", "Map Control"],
    Striker: ["Support"],
    Rauora: ["Support", "Map Control"],

    // Wild
    Wildcard: ["Anti-Breach", "Crown Control", "Trapper", "Anti-Entry", "Intel", "Support", "Hard-Breach", "Map Control", "Front Line", "Anti-Gadget", "Breach"]
};
